# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"




  # config.vm.network "forwarded_port", guest: 80, host: 8080


  # config.vm.network "private_network", ip: "192.168.33.10"


  # config.vm.network "public_network"


  
  
  
  
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.cpus = "2"
  end
  
  #Multimachine setup
  config.vm.define "master", primary: true do | master |
    master.vm.hostname = "master"
    master.vm.synced_folder "../vagrant", "/var/www"
    master.vm.network "private_network", ip: "192.168.56.20"
    master.vm.provision "shell", path: "../ansible/masterscript.sh", privileged: false
  end
  # /Users/jakpu/dev/practice/AltSchool/semester_2/exam/ansible
  config.vm.define "slave" do | slave |
    slave.vm.hostname = "slave"
    slave.vm.synced_folder "../ansible", "/etc/ansible"
    slave.vm.network "private_network", ip: "192.168.56.21"
    slave.vm.provision "shell", path: "slavescript.sh", privileged: false
  end



  config.vm.provision "shell", path: "provision.sh", privileged: false

end
